using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Win32;

namespace WpfTest.DataBinding
{
    class FcnTestTools
    {
        /// <summary>
        /// choose a file and print its filename
        /// </summary>
        public static void ChooseFileToOpen()
        {
            OpenFileDialog dialog = new OpenFileDialog();
            dialog.Title = "mission load";
            //dialog.Filter = "233|*.txt|all files|*.*";
            dialog.InitialDirectory = "C:";
            dialog.ShowDialog();
            Console.WriteLine(dialog.FileName);
        }

        /// <summary>
        /// test funcntion that generated by direct function in the .cpp file
        /// </summary>
        public static void TestDirectImportFcn()
        {
            Console.WriteLine("--------test simple direct function---------");
            int a = 135;
            int b = 5;
            Console.WriteLine("-------------------");
            Console.WriteLine(ReferDll.Add(a, b));
            Console.WriteLine(ReferDll.Minus(a, b));
            Console.WriteLine(ReferDll.g_Multi(a, b));
            Console.WriteLine(ReferDll.g_Div(a, b));

            int[] arr1 = { 1, 2, 3 };
            int[] arr2 = { 3, 2, 5 };
            Console.WriteLine(ReferDll.DotProd(arr1, arr2, arr1.Length));

            string str = "hello world";
            ReferDll.CharArr(str, str.Length);
            Console.WriteLine();
        }

        /// <summary>
        /// test static method in the class
        /// for non-static method, it is also the same
        /// </summary>
        public static void TestStaticFcnImportFromClass()
        {
            Console.WriteLine("------test static function that in the class--------");
            ImportFcnClass.PrintInfo("23333");
            Console.WriteLine(ImportFcnClass.Add(5, 2));

            Console.WriteLine(ImportFcnClass.minus(5, 2));
            Console.WriteLine(ImportFcnClass.AddMnius(1, 2, 3));
        }

        /// <summary>
        /// test function parameters with the stuct
        /// how the struct data convert with C++ and C#
        /// </summary>
        public static void TestImportFcnWithStruct()
        {
            Console.WriteLine("------struct import test-------");
            HSCAN_MSG[] msg = new HSCAN_MSG[5]; //发送缓冲区大小可根据需要设置；  
            for (int yy = 0; yy < msg.Length; yy++)
            {
                msg[yy] = new HSCAN_MSG();
                msg[yy].Port = (byte)((yy + 1) * 10);
            }

            for (int i = 1; i < 5; i++)
            {
                //msg[i] = ImportFcnClass.GenerateMsg();
                
            }
            Console.WriteLine("port : " + ImportFcnClass.HSCAN_SendCANMessage(0x0, 0x0, msg, msg.Count()));

        }

    }
}
